### PR TITLE
Skunkworks data request

### PR DESCRIPTION
**Pull request by jessli615**
#### What's this PR do?
It creates a bar chart to show the total counts of MAMs across different cio newsletter buckets by month. 

#### Where should the reviewer start?
From the start!

#### What are the relevant tickets/trello cards?
https://trello.com/c/euZoIqIS/1410-skunkworks-user-retention

### CODE REVIEW

**Comment by jessli615** [comment]
skunkworks Forgot to add final chart!

**Comment by sohaibhasan** [comment]
Is the goal of the chart to show changes month over month? If so, I feel like you would be better off making month a group rather than a facet. That would give you three bars in a row for askfreddie, then roundup, and so on. If we're trying to compare month over month, this view makes me have to jump from panel to panel

**Comment by jessli615** [comment]
@sohaibhasan hm yeah good point, I tried to group by month while removing the facet (see below) but it produced this..

ggplot(skunkworks_pct, aes(x=variable, y=value, group = month_active, fill=variable)) + geom_bar(stat="identity") +  geom_text(aes(label=scales::percent(value)), vjust=2, position = position_dodge(width=0.9),  size=2) + labs(x = 'Newsletter', y = 'Percentage of MAMS') + scale_y_continuous(labels = scales::percent_format(accuracy = 1)) + theme(axis.text.x = element_text(angle = 20, hjust = 1))

skunkworks

**Comment by sohaibhasan** [comment]
@jessli615 You need to dodge the bars like you did the labels. Can be done by adding `position = 'dodge'` inside geom_bar

**Pull request merged**
